Prevent database is locked errors
Since there are only SELECT statements, the database can be opened as read-only preventing:

Error: SQLITE_BUSY: database is locked
    at Error (native)